spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 5656

#  error:
#    include-message: always

application:
  jwt:
    secretKey: Aisuluu
    tokenPrefix: Bearer
    expirationDateAfterDays: 30

